import { gloriaHallelujah, pacifico, robotoFlex } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: process.env.SITE_NAME || "Site Title here",
  description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn(
				pacifico.variable,
				gloriaHallelujah.variable,
				robotoFlex.variable,
			)}
		>
			<body className={robotoFlex.className}>{children}</body>
		</html>
	);
}
