import type { Metadata } from "next";
import "./globals.css";
import { gloriaHallelujah, pacifico, robotoFlex } from "@/lib/fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn(
				pacifico.variable,
				gloriaHallelujah.variable,
				robotoFlex.variable,
			)}
		>
			<body className={robotoFlex.className}>{children}</body>
		</html>
	);
}
